### ISSUE TITLE
Change CircleCI jobs to use matrix stanza

### ISSUE THREAD

**Issue by jilleJr** [jilleJr/Newtonsoft.Json-for-Unity.Converters#28]
## Description

The test-unity-$version is highly repeated sections in the `.circleci/config.yml` and can be collapsed into a single job using parameters and the [matrix stanza](https://circleci.com/docs/2.0/configuration-reference/#matrix-requires-version-21)

## Motivation

Easier to read and easier to manage.

Also adds ease of adding builds for .NET Standard 2.0 vs .NET Framework 4.x tests

## Suggested solution

```yaml

jobs:
  test-unity:
    # snip

    parameters:
      unity-version:
        type: string
      api-compatibility:
        type: string
        default: netstandard2.0
      scripting-runtime:
        type: string
        default: mono
      downgrade-asmdefs:
        type: boolean
        default: false

    docker:
      - image: applejag/newtonsoft.json-for-unity.converters.package-unity-tester:v1-<< parameters.unity-version >>

    steps:
      # snip

      - when:
          condition: << parameters.downgrade-asmdefs >>
          steps:
            - run:
                name: Downgrade Unity project to 2018.x
                command: # snip

      #snip

workflows:
  test:
    jobs:
      - test-unity:
          unity-version: 2018.4.14f1
          downgrade-asmdefs: true

          matrix:
            parameters:
              api-compatibility: ["netstandard2.0", "net4.x"]
              scripting-runtime: ["mono", "il2cpp"]
          filters:
            branches:
              <<: *WORKFLOW_TEST_FILTER

      - test-unity:
          matrix:
            parameters:
              unity-version: ["2019.2.11f1", "2020.1.0b6"]
              api-compatibility: ["netstandard2.0", "net4.x"]
              scripting-runtime: ["mono", "il2cpp"]
          filters:
            branches:
              <<: *WORKFLOW_TEST_FILTER
```

## Inspiration sources

CircleCI docs:
- Matrix: https://circleci.com/docs/2.0/configuration-reference/#matrix-requires-version-21
- Parameters syntax: https://circleci.com/docs/2.0/reusing-config/#parameter-syntax
